version: '3.4'

services:
  weaviate:
    image: semitechnologies/weaviate:1.23.0
    command:
      - --host
      - 0.0.0.0
      - --port
      - "8080"
      - --scheme
      - http
    ports:
      - "8080:8080"
      - "50051:50051"
    environment:
      OPENAI_APIKEY: ${OPENAI_API_KEY}
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      DEFAULT_VECTORIZER_MODULE: "text2vec-openai"
      ENABLE_MODULES: "text2vec-openai,generative-openai"
    volumes:
      - weaviate_data:/var/lib/weaviate
    restart: on-failure

  streamlit-app:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - weaviate_data:/piazza_data

volumes:
  weaviate_data:
    driver: local
